## Importaciones

In [42]:
# Importaciones generales
from pathlib import Path
from dataclasses import dataclass
from typing import Any

import gc
import json

import numpy as np
import pandas as pd
import torch

# Hugging Face datasets
from datasets import load_from_disk

# Hugging Face transformers
from transformers import (
    WhisperProcessor,
    WhisperForConditionalGeneration,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments
)

# Métricas
import evaluate

## Conexión a Mongo

In [2]:
# Conexión con Mongo
cliente = MongoClient('mongodb://pialarabi:p13l3r3b1_.@27.0.172.67/pialara')

iabd_db = cliente.pialara
audios_coll = iabd_db.audios

# Verificar la conexión a MongoDB
try:
    cliente.admin.command("ping")
    print("Conexión correcta a MongoDB")
except Exception as e:
    print("Error de conexión:")
    print(e)

Conexión correcta a MongoDB

## Datasets

Se hace un dataset para cada usuario que tenga más de 500 audios.

In [4]:
# Revisamos un documento de ejemplo para ver la estructura
doc_ejemplo = audios_coll.find_one()

doc_ejemplo

{'_id': ObjectId('642462abdda7c982b10c7d4a'),
 'aws_object_id': '6424622bdda7c982b10c7d39_1680106156.wav',
 'usuario': {'id': ObjectId('6424622bdda7c982b10c7d39'),
  'mail': 'rodolfo@jennifervk.com',
  'nombre': 'Prueba Rodolfa',
  'parent': 'jennifer@vk.com'},
 'fecha': datetime.datetime(2023, 3, 29, 18, 9, 15, 866000),
 'texto': {'id': ObjectId('640cb6abbd72df924a9f6196'),
  'texto': 'La bata tiene veinte botones.',
  'tag': '1b1',
  'tipo': 'syllabus'},
 'duracion': 3,
 'metadata': {'tipo_frase': 'larga', 'fonema': 'b', 'posicion_lengua': 'baja'},
 'schema_version': 2}

In [5]:
# Mostramos solo los campos principales del documento
doc_ejemplo.keys()

dict_keys(['_id', 'aws_object_id', 'usuario', 'fecha', 'texto', 'duracion', 'metadata', 'schema_version'])

In [12]:
# Obtenemos los usuarios con más de 500 audios
pipeline_usuarios = [
    {
        "$group": {
            "_id": "$usuario.id",
            "nombre": {"$first": "$usuario.nombre"},
            "total_audios": {"$sum": 1}
        }
    },
    {
        "$match": {
            "total_audios": {"$gt": 500}
        }
    },
    {
        "$sort": {
            "total_audios": -1
        }
    }
]

usuarios_mas_500 = list(audios_coll.aggregate(pipeline_usuarios))

print("Usuarios con más de 500 audios:", len(usuarios_mas_500))

usuarios_mas_500[:10]

Usuarios con más de 500 audios: 16

[{'_id': ObjectId('662819171ef22d020bf25236'),
  'nombre': 'Tomás Manuel Bermudez',
  'total_audios': 12706},
 {'_id': ObjectId('6628187f1ef22d020bf25232'),
  'nombre': 'Verónica Marco',
  'total_audios': 4746},
 {'_id': ObjectId('6564612039048d0f405c668a'),
  'nombre': 'Maria Gertrudis Agullo Esclapez',
  'total_audios': 1610},
 {'_id': ObjectId('6564622239048d0f405c669c'),
  'nombre': 'Enrique Sanchez Fernandez',
  'total_audios': 1578},
 {'_id': ObjectId('662a3a80d3f7e3d0e780eefd'),
  'nombre': 'Ernesto Belenguer Bedmar',
  'total_audios': 1538},
 {'_id': ObjectId('6564637c39048d0f405c66c0'),
  'nombre': 'Alba Serrano Rico',
  'total_audios': 1305},
 {'_id': ObjectId('6564630939048d0f405c66b6'),
  'nombre': 'Raquel Villegas Gonzalvez',
  'total_audios': 1207},
 {'_id': ObjectId('663a0964aa128a933ae401b1'),
  'nombre': 'Laura Moreno',
  'total_audios': 1026},
 {'_id': ObjectId('64412b83a669ed28de6f78ff'),
  'nombre': 'Cristina Román Durá',
  'total_audios': 693},
 {'_id': ObjectId('663a0843aa128a933ae4019e'),
  'nombre': 'Eva Ortiz',
  'total_audios': 637}]

In [13]:
# Limpiamos el nombre para usarlo como nombre de carpeta
def limpiar_nombre_carpeta(nombre):
    nombre = str(nombre).strip().lower()
    nombre = re.sub(r"[^\w\s-]", "", nombre, flags=re.UNICODE)
    nombre = re.sub(r"\s+", "_", nombre)
    return nombre

In [14]:
# Carpeta donde guardaremos los datasets por usuario
ruta_base_datasets_usuario = Path("C:/lara/datasets_por_usuario")
ruta_base_datasets_usuario.mkdir(parents=True, exist_ok=True)

datasets_generados = []

# Generamos un dataset independiente por cada usuario
for usuario in usuarios_mas_500:
    usuario_id = usuario["_id"]
    usuario_nombre = usuario.get("nombre", "usuario_sin_nombre")
    total_audios = usuario.get("total_audios", 0)

    nombre_carpeta = limpiar_nombre_carpeta(usuario_nombre)
    ruta_dataset_usuario = ruta_base_datasets_usuario / nombre_carpeta

    print("Procesando usuario:", usuario_nombre)
    print("Total audios en Mongo:", total_audios)
    print("Ruta dataset:", ruta_dataset_usuario)

    cursor = audios_coll.find(
        {
            "usuario.id": usuario_id,
            "aws_object_id": {"$exists": True, "$ne": None},
            "texto.texto": {"$exists": True, "$ne": None}
        },
        {
            "_id": 0,
            "aws_object_id": 1,
            "texto.texto": 1
        }
    )

    registros = []

    # Extraemos únicamente audio y texto
    for doc in cursor:
        registros.append({
            "audio": doc.get("aws_object_id"),
            "texto": doc.get("texto", {}).get("texto")
        })

    if len(registros) == 0:
        print("No se encontraron registros válidos para este usuario.")
        print("----------------------------------------")
        continue

    dataset_usuario = Dataset.from_list(registros)

    dataset_usuario.save_to_disk(str(ruta_dataset_usuario))

    datasets_generados.append({
        "usuario": usuario_nombre,
        "total_audios_mongo": total_audios,
        "total_registros_dataset": len(dataset_usuario),
        "ruta_dataset": str(ruta_dataset_usuario)
    })

    print("Dataset guardado correctamente")
    print("Registros guardados:", len(dataset_usuario))
    print("----------------------------------------")

Procesando usuario: Tomás Manuel Bermudez
Total audios en Mongo: 12706
Ruta dataset: C:\lara\datasets_por_usuario\tomás_manuel_bermudez

Saving the dataset (0/1 shards):   0%|          | 0/12706 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 12706
----------------------------------------
Procesando usuario: Verónica Marco
Total audios en Mongo: 4746
Ruta dataset: C:\lara\datasets_por_usuario\verónica_marco

Saving the dataset (0/1 shards):   0%|          | 0/4746 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 4746
----------------------------------------
Procesando usuario: Maria Gertrudis Agullo Esclapez
Total audios en Mongo: 1610
Ruta dataset: C:\lara\datasets_por_usuario\maria_gertrudis_agullo_esclapez

Saving the dataset (0/1 shards):   0%|          | 0/1610 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1610
----------------------------------------
Procesando usuario: Enrique Sanchez Fernandez
Total audios en Mongo: 1578
Ruta dataset: C:\lara\datasets_por_usuario\enrique_sanchez_fernandez

Saving the dataset (0/1 shards):   0%|          | 0/1578 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1578
----------------------------------------
Procesando usuario: Ernesto Belenguer Bedmar
Total audios en Mongo: 1538
Ruta dataset: C:\lara\datasets_por_usuario\ernesto_belenguer_bedmar

Saving the dataset (0/1 shards):   0%|          | 0/1538 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1538
----------------------------------------
Procesando usuario: Alba Serrano Rico
Total audios en Mongo: 1305
Ruta dataset: C:\lara\datasets_por_usuario\alba_serrano_rico

Saving the dataset (0/1 shards):   0%|          | 0/1305 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1305
----------------------------------------
Procesando usuario: Raquel Villegas Gonzalvez
Total audios en Mongo: 1207
Ruta dataset: C:\lara\datasets_por_usuario\raquel_villegas_gonzalvez

Saving the dataset (0/1 shards):   0%|          | 0/1207 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1207
----------------------------------------
Procesando usuario: Laura Moreno
Total audios en Mongo: 1026
Ruta dataset: C:\lara\datasets_por_usuario\laura_moreno

Saving the dataset (0/1 shards):   0%|          | 0/1026 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 1026
----------------------------------------
Procesando usuario: Cristina Román Durá
Total audios en Mongo: 693
Ruta dataset: C:\lara\datasets_por_usuario\cristina_román_durá

Saving the dataset (0/1 shards):   0%|          | 0/693 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 693
----------------------------------------
Procesando usuario: Eva Ortiz
Total audios en Mongo: 637
Ruta dataset: C:\lara\datasets_por_usuario\eva_ortiz

Saving the dataset (0/1 shards):   0%|          | 0/637 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 637
----------------------------------------
Procesando usuario: David . laville
Total audios en Mongo: 632
Ruta dataset: C:\lara\datasets_por_usuario\david_laville

Saving the dataset (0/1 shards):   0%|          | 0/632 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 632
----------------------------------------
Procesando usuario: Javier
Total audios en Mongo: 596
Ruta dataset: C:\lara\datasets_por_usuario\javier

Saving the dataset (0/1 shards):   0%|          | 0/596 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 596
----------------------------------------
Procesando usuario: Pablo Ybarra Gomariz
Total audios en Mongo: 584
Ruta dataset: C:\lara\datasets_por_usuario\pablo_ybarra_gomariz

Saving the dataset (0/1 shards):   0%|          | 0/584 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 584
----------------------------------------
Procesando usuario: Aurora Montiel mora
Total audios en Mongo: 567
Ruta dataset: C:\lara\datasets_por_usuario\aurora_montiel_mora

Saving the dataset (0/1 shards):   0%|          | 0/567 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 567
----------------------------------------
Procesando usuario: Cristina Román Durá
Total audios en Mongo: 556
Ruta dataset: C:\lara\datasets_por_usuario\cristina_román_durá

Saving the dataset (0/1 shards):   0%|          | 0/556 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 556
----------------------------------------
Procesando usuario: Alvaro amoros
Total audios en Mongo: 501
Ruta dataset: C:\lara\datasets_por_usuario\alvaro_amoros

Saving the dataset (0/1 shards):   0%|          | 0/501 [00:00<?, ? examples/s]

Dataset guardado correctamente
Registros guardados: 501
----------------------------------------

In [15]:
# Creamos una tabla resumen de los datasets generados
df_datasets_generados = pd.DataFrame(datasets_generados)

df_datasets_generados

,usuario,total_audios_mongo,total_registros_dataset,ruta_dataset
0,Tomás Manuel Bermudez,12706,12706,C:\lara\datasets_por_usuario\tomás_manuel_berm...
1,Verónica Marco,4746,4746,C:\lara\datasets_por_usuario\verónica_marco
2,Maria Gertrudis Agullo Esclapez,1610,1610,C:\lara\datasets_por_usuario\maria_gertrudis_a...
3,Enrique Sanchez Fernandez,1578,1578,C:\lara\datasets_por_usuario\enrique_sanchez_f...
4,Ernesto Belenguer Bedmar,1538,1538,C:\lara\datasets_por_usuario\ernesto_belenguer...
5,Alba Serrano Rico,1305,1305,C:\lara\datasets_por_usuario\alba_serrano_rico
6,Raquel Villegas Gonzalvez,1207,1207,C:\lara\datasets_por_usuario\raquel_villegas_g...
7,Laura Moreno,1026,1026,C:\lara\datasets_por_usuario\laura_moreno
8,Cristina Román Durá,693,693,C:\lara\datasets_por_usuario\cristina_román_durá
9,Eva Ortiz,637,637,C:\lara\datasets_por_usuario\eva_ortiz
10,David . laville,632,632,C:\lara\datasets_por_usuario\david_laville
11,Javier,596,596,C:\lara\datasets_por_usuario\javier
12,Pablo Ybarra Gomariz,584,584,C:\lara\datasets_por_usuario\pablo_ybarra_gomariz
13,Aurora Montiel mora,567,567,C:\lara\datasets_por_usuario\aurora_montiel_mora
14,Cristina Román Durá,556,556,C:\lara\datasets_por_usuario\cristina_román_durá
15,Alvaro amoros,501,501,C:\lara\datasets_por_usuario\alvaro_amoros

In [16]:
# Guardamos un resumen para saber qué datasets se han generado
ruta_resumen = ruta_base_datasets_usuario / "resumen_datasets_por_usuario.csv"

df_datasets_generados.to_csv(ruta_resumen, index=False, encoding="utf-8-sig")

print("Resumen guardado en:", ruta_resumen)

Resumen guardado en: C:\lara\datasets_por_usuario\resumen_datasets_por_usuario.csv

In [17]:
# Cargamos el primer dataset generado para comprobar que está correcto
ruta_primer_dataset = df_datasets_generados.iloc[0]["ruta_dataset"]

dataset_prueba = load_from_disk(ruta_primer_dataset)

dataset_prueba

Dataset({
    features: ['audio', 'texto'],
    num_rows: 12706
})

In [19]:
# Rutas de entrada y salida
ruta_base_datasets_usuario = Path("C:/lara/datasets_por_usuario")
ruta_base_splits_usuario = Path("C:/lara/datasets_por_usuario_split")

ruta_base_splits_usuario.mkdir(parents=True, exist_ok=True)

SEED = 42
PORCENTAJE_TEST = 0.2

In [20]:
# Buscamos carpetas que parezcan datasets guardados con save_to_disk
rutas_datasets_usuario = []

for ruta in ruta_base_datasets_usuario.iterdir():
    if ruta.is_dir() and (ruta / "dataset_info.json").exists():
        rutas_datasets_usuario.append(ruta)

print("Datasets encontrados:", len(rutas_datasets_usuario))

for ruta in rutas_datasets_usuario:
    print(ruta.name)

Datasets encontrados: 15
alba_serrano_rico
alvaro_amoros
aurora_montiel_mora
cristina_román_durá
david_laville
enrique_sanchez_fernandez
ernesto_belenguer_bedmar
eva_ortiz
javier
laura_moreno
maria_gertrudis_agullo_esclapez
pablo_ybarra_gomariz
raquel_villegas_gonzalvez
tomás_manuel_bermudez
verónica_marco

In [ ]:
# Cristina viene duplicada en la base de datos, se han creado dos dataset y el último pisa al primero.
# Para evitar esto, eegeneramos solo el dataset de Cristina Román Durá agrupando por nombre
usuario_nombre = "Cristina Román Durá"

ruta_dataset_cristina = Path("C:/lara/datasets_por_usuario") / limpiar_nombre_carpeta(usuario_nombre)

cursor = audios_coll.find(
    {
        "usuario.nombre": usuario_nombre,
        "aws_object_id": {"$exists": True, "$ne": None},
        "texto.texto": {"$exists": True, "$ne": None}
    },
    {
        "_id": 0,
        "aws_object_id": 1,
        "texto.texto": 1
    }
)

registros = []

# Extraemos únicamente audio y texto
for doc in cursor:
    registros.append({
        "audio": doc.get("aws_object_id"),
        "texto": doc.get("texto", {}).get("texto")
    })

dataset_cristina = Dataset.from_list(registros)

dataset_cristina.save_to_disk(str(ruta_dataset_cristina))

print("Dataset regenerado:", ruta_dataset_cristina)
print("Total de audios guardados:", len(dataset_cristina))

Saving the dataset (0/1 shards):   0%|          | 0/1249 [00:00<?, ? examples/s]

Dataset regenerado: C:\lara\datasets_por_usuario\cristina_román_durá
Total de audios guardados: 1249

In [25]:
# Buscamos las carpetas que contienen datasets guardados
rutas_datasets_usuario = []

for ruta in ruta_base_datasets_usuario.iterdir():
    if ruta.is_dir() and (ruta / "dataset_info.json").exists():
        rutas_datasets_usuario.append(ruta)

print("Datasets encontrados:", len(rutas_datasets_usuario))

for ruta in rutas_datasets_usuario:
    print(ruta.name)

Datasets encontrados: 15
alba_serrano_rico
alvaro_amoros
aurora_montiel_mora
cristina_román_durá
david_laville
enrique_sanchez_fernandez
ernesto_belenguer_bedmar
eva_ortiz
javier
laura_moreno
maria_gertrudis_agullo_esclapez
pablo_ybarra_gomariz
raquel_villegas_gonzalvez
tomás_manuel_bermudez
verónica_marco

In [26]:
resumen_splits = []

# Generamos train/test para cada dataset de usuario
for ruta_dataset in rutas_datasets_usuario:
    nombre_dataset = ruta_dataset.name
    ruta_salida = ruta_base_splits_usuario / nombre_dataset

    print("Procesando dataset:", nombre_dataset)

    dataset_usuario = load_from_disk(str(ruta_dataset))

    split_usuario = dataset_usuario.train_test_split(
        test_size=PORCENTAJE_TEST,
        seed=SEED,
        shuffle=True
    )

    dataset_split = DatasetDict({
        "train": split_usuario["train"],
        "test": split_usuario["test"]
    })

    dataset_split.save_to_disk(str(ruta_salida))

    resumen_splits.append({
        "dataset": nombre_dataset,
        "total": len(dataset_usuario),
        "train": len(dataset_split["train"]),
        "test": len(dataset_split["test"]),
        "ruta_split": str(ruta_salida)
    })

    print("Total:", len(dataset_usuario))
    print("Train:", len(dataset_split["train"]))
    print("Test:", len(dataset_split["test"]))
    print("Guardado en:", ruta_salida)
    print("----------------------------------------")

Procesando dataset: alba_serrano_rico

Saving the dataset (0/1 shards):   0%|          | 0/1044 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/261 [00:00<?, ? examples/s]

Total: 1305
Train: 1044
Test: 261
Guardado en: C:\lara\datasets_por_usuario_split\alba_serrano_rico
----------------------------------------
Procesando dataset: alvaro_amoros

Saving the dataset (0/1 shards):   0%|          | 0/400 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/101 [00:00<?, ? examples/s]

Total: 501
Train: 400
Test: 101
Guardado en: C:\lara\datasets_por_usuario_split\alvaro_amoros
----------------------------------------
Procesando dataset: aurora_montiel_mora

Saving the dataset (0/1 shards):   0%|          | 0/453 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/114 [00:00<?, ? examples/s]

Total: 567
Train: 453
Test: 114
Guardado en: C:\lara\datasets_por_usuario_split\aurora_montiel_mora
----------------------------------------
Procesando dataset: cristina_román_durá

Saving the dataset (0/1 shards):   0%|          | 0/999 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/250 [00:00<?, ? examples/s]

Total: 1249
Train: 999
Test: 250
Guardado en: C:\lara\datasets_por_usuario_split\cristina_román_durá
----------------------------------------
Procesando dataset: david_laville

Saving the dataset (0/1 shards):   0%|          | 0/505 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/127 [00:00<?, ? examples/s]

Total: 632
Train: 505
Test: 127
Guardado en: C:\lara\datasets_por_usuario_split\david_laville
----------------------------------------
Procesando dataset: enrique_sanchez_fernandez

Saving the dataset (0/1 shards):   0%|          | 0/1262 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/316 [00:00<?, ? examples/s]

Total: 1578
Train: 1262
Test: 316
Guardado en: C:\lara\datasets_por_usuario_split\enrique_sanchez_fernandez
----------------------------------------
Procesando dataset: ernesto_belenguer_bedmar

Saving the dataset (0/1 shards):   0%|          | 0/1230 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/308 [00:00<?, ? examples/s]

Total: 1538
Train: 1230
Test: 308
Guardado en: C:\lara\datasets_por_usuario_split\ernesto_belenguer_bedmar
----------------------------------------
Procesando dataset: eva_ortiz

Saving the dataset (0/1 shards):   0%|          | 0/509 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/128 [00:00<?, ? examples/s]

Total: 637
Train: 509
Test: 128
Guardado en: C:\lara\datasets_por_usuario_split\eva_ortiz
----------------------------------------
Procesando dataset: javier

Saving the dataset (0/1 shards):   0%|          | 0/476 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/120 [00:00<?, ? examples/s]

Total: 596
Train: 476
Test: 120
Guardado en: C:\lara\datasets_por_usuario_split\javier
----------------------------------------
Procesando dataset: laura_moreno

Saving the dataset (0/1 shards):   0%|          | 0/820 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/206 [00:00<?, ? examples/s]

Total: 1026
Train: 820
Test: 206
Guardado en: C:\lara\datasets_por_usuario_split\laura_moreno
----------------------------------------
Procesando dataset: maria_gertrudis_agullo_esclapez

Saving the dataset (0/1 shards):   0%|          | 0/1288 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/322 [00:00<?, ? examples/s]

Total: 1610
Train: 1288
Test: 322
Guardado en: C:\lara\datasets_por_usuario_split\maria_gertrudis_agullo_esclapez
----------------------------------------
Procesando dataset: pablo_ybarra_gomariz

Saving the dataset (0/1 shards):   0%|          | 0/467 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/117 [00:00<?, ? examples/s]

Total: 584
Train: 467
Test: 117
Guardado en: C:\lara\datasets_por_usuario_split\pablo_ybarra_gomariz
----------------------------------------
Procesando dataset: raquel_villegas_gonzalvez

Saving the dataset (0/1 shards):   0%|          | 0/965 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/242 [00:00<?, ? examples/s]

Total: 1207
Train: 965
Test: 242
Guardado en: C:\lara\datasets_por_usuario_split\raquel_villegas_gonzalvez
----------------------------------------
Procesando dataset: tomás_manuel_bermudez

Saving the dataset (0/1 shards):   0%|          | 0/10164 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/2542 [00:00<?, ? examples/s]

Total: 12706
Train: 10164
Test: 2542
Guardado en: C:\lara\datasets_por_usuario_split\tomás_manuel_bermudez
----------------------------------------
Procesando dataset: verónica_marco

Saving the dataset (0/1 shards):   0%|          | 0/3796 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/950 [00:00<?, ? examples/s]

Total: 4746
Train: 3796
Test: 950
Guardado en: C:\lara\datasets_por_usuario_split\verónica_marco
----------------------------------------

In [27]:
# Resumen de splits generados
df_resumen_splits = pd.DataFrame(resumen_splits)

df_resumen_splits

,dataset,total,train,test,ruta_split
0,alba_serrano_rico,1305,1044,261,C:\lara\datasets_por_usuario_split\alba_serran...
1,alvaro_amoros,501,400,101,C:\lara\datasets_por_usuario_split\alvaro_amoros
2,aurora_montiel_mora,567,453,114,C:\lara\datasets_por_usuario_split\aurora_mont...
3,cristina_román_durá,1249,999,250,C:\lara\datasets_por_usuario_split\cristina_ro...
4,david_laville,632,505,127,C:\lara\datasets_por_usuario_split\david_laville
5,enrique_sanchez_fernandez,1578,1262,316,C:\lara\datasets_por_usuario_split\enrique_san...
6,ernesto_belenguer_bedmar,1538,1230,308,C:\lara\datasets_por_usuario_split\ernesto_bel...
7,eva_ortiz,637,509,128,C:\lara\datasets_por_usuario_split\eva_ortiz
8,javier,596,476,120,C:\lara\datasets_por_usuario_split\javier
9,laura_moreno,1026,820,206,C:\lara\datasets_por_usuario_split\laura_moreno
10,maria_gertrudis_agullo_esclapez,1610,1288,322,C:\lara\datasets_por_usuario_split\maria_gertr...
11,pablo_ybarra_gomariz,584,467,117,C:\lara\datasets_por_usuario_split\pablo_ybarr...
12,raquel_villegas_gonzalvez,1207,965,242,C:\lara\datasets_por_usuario_split\raquel_vill...
13,tomás_manuel_bermudez,12706,10164,2542,C:\lara\datasets_por_usuario_split\tomás_manue...
14,verónica_marco,4746,3796,950,C:\lara\datasets_por_usuario_split\verónica_marco

In [28]:
# Guardamos el resumen de los splits
ruta_resumen_splits = ruta_base_splits_usuario / "resumen_splits_por_usuario.csv"

df_resumen_splits.to_csv(ruta_resumen_splits, index=False, encoding="utf-8-sig")

print("Resumen guardado en:", ruta_resumen_splits)

Resumen guardado en: C:\lara\datasets_por_usuario_split\resumen_splits_por_usuario.csv

In [29]:
# Cargamos el primer dataset dividido para comprobarlo
ruta_primer_split = df_resumen_splits.iloc[0]["ruta_split"]

dataset_prueba_split = load_from_disk(ruta_primer_split)

dataset_prueba_split

DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1044
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 261
    })
})

In [30]:
print("Train:", len(dataset_prueba_split["train"]))
print("Test:", len(dataset_prueba_split["test"]))

dataset_prueba_split["train"][:5]

Train: 1044
Test: 261

{'audio': ['6564637c39048d0f405c66c0_1738580881.wav',
  '6564637c39048d0f405c66c0_1710156460.wav',
  '6564637c39048d0f405c66c0_1739788936.wav',
  '6564637c39048d0f405c66c0_1711363349.wav',
  '6564637c39048d0f405c66c0_1714385155.wav'],
 'texto': ['EN LA COLINA HAY MULAS.',
  'ESTAS GAFAS ME ESTÁN GRANDES.',
  'EN EL ZOOLÓGICO HABÍA CIGÜEÑAS Y CIGARRAS.',
  'COMIMOS EMPANADA EN AMPURIAS.',
  'LAS CALLES DE CORAZÓN DE JESÚS ESTÁN LLENAS']}

## Preparación de los dataset

In [31]:
# Configuración de rutas
RUTA_BASE_AUDIOS = Path("C:/Lara/audios-230426/audios-s3")
SAMPLING_RATE = 16000

# Probamos con el primer split generado
ruta_primer_split = df_resumen_splits.iloc[0]["ruta_split"]
dataset_prueba_split = load_from_disk(ruta_primer_split)

print(dataset_prueba_split)

DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1044
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 261
    })
})

In [32]:
# Cargamos cada audio desde disco usando librosa
def cargar_audio_con_librosa(ejemplo):
    nombre_audio = ejemplo["audio"]
    ruta_audio = RUTA_BASE_AUDIOS / nombre_audio

    try:
        audio_array, sampling_rate = librosa.load(
            str(ruta_audio),
            sr=SAMPLING_RATE,
            mono=True
        )

        ejemplo["audio"] = {
            "array": audio_array,
            "sampling_rate": sampling_rate
        }

        ejemplo["audio_valido"] = True
        ejemplo["error_audio"] = ""

    except Exception as e:
        ejemplo["audio"] = None
        ejemplo["audio_valido"] = False
        ejemplo["error_audio"] = str(e)

    return ejemplo

In [33]:
# Aplicamos la carga de audio a train y test
dataset_prueba_preparado = dataset_prueba_split.map(
    cargar_audio_con_librosa,
    desc="Cargando audios con librosa"
)

dataset_prueba_preparado

Cargando audios con librosa:   0%|          | 0/1044 [00:00<?, ? examples/s]

C:\Users\abelg\AppData\Local\Temp\ipykernel_15652\2369524765.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sampling_rate = librosa.load(
c:\Users\abelg\AppData\Local\Programs\Python\Python313\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)
C:\Users\abelg\AppData\Local\Temp\ipykernel_15652\2369524765.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sampling_rate = librosa.load(
c:\Users\abelg\AppData\Local\Programs\Python\Python313\Lib\site-packages\librosa\core\audio.py:184: FutureWarning: librosa.core.audio.__audioread_load
	Deprecated as of librosa version 0.10.0.
	It will be removed in librosa version 1.0.
  y, sr_native = __audioread_load(path, offset, duration, dtype)

Cargando audios con librosa:   0%|          | 0/261 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['audio', 'texto', 'audio_valido', 'error_audio'],
        num_rows: 1044
    })
    test: Dataset({
        features: ['audio', 'texto', 'audio_valido', 'error_audio'],
        num_rows: 261
    })
})

In [34]:
# Eliminamos registros donde el audio no se haya podido cargar
dataset_prueba_preparado = dataset_prueba_preparado.filter(
    lambda ejemplo: ejemplo["audio_valido"] == True
)

# Quitamos columnas auxiliares
dataset_prueba_preparado = dataset_prueba_preparado.remove_columns([
    "audio_valido",
    "error_audio"
])

dataset_prueba_preparado

Filter:   0%|          | 0/1044 [00:00<?, ? examples/s]

Filter:   0%|          | 0/261 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 844
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 203
    })
})

In [35]:
# Guardamos el dataset preparado con audios cargados
ruta_salida_preparado = Path("C:/lara/datasets_por_usuario_split_preparados") / Path(ruta_primer_split).name
ruta_salida_preparado.parent.mkdir(parents=True, exist_ok=True)

dataset_prueba_preparado.save_to_disk(str(ruta_salida_preparado))

print("Dataset preparado guardado en:", ruta_salida_preparado)

Saving the dataset (0/1 shards):   0%|          | 0/844 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/203 [00:00<?, ? examples/s]

Dataset preparado guardado en: C:\lara\datasets_por_usuario_split_preparados\alba_serrano_rico

In [36]:
# Escuchamos un audio del dataset preparado para comprobar que se ha cargado bien
indice_audio = 0

ejemplo = dataset_prueba_preparado["train"][indice_audio]

audio_array = ejemplo["audio"]["array"]
sampling_rate = ejemplo["audio"]["sampling_rate"]
texto = ejemplo["texto"]

print("Texto:", texto)
print("Sampling rate:", sampling_rate)
print("Duración aproximada:", round(len(audio_array) / sampling_rate, 2), "segundos")

display(IPythonAudio(audio_array, rate=sampling_rate))

Texto: EN LA COLINA HAY MULAS.
Sampling rate: 16000
Duración aproximada: 3.35 segundos

In [37]:
# Preparamos todos los datasets por usuario cargando los audios con librosa
ruta_base_splits_usuario = Path("C:/lara/datasets_por_usuario_split")
ruta_base_splits_preparados = Path("C:/lara/datasets_por_usuario_split_preparados")

ruta_base_splits_preparados.mkdir(parents=True, exist_ok=True)

RUTA_BASE_AUDIOS = Path("C:/Lara/audios-230426/audios-s3")
SAMPLING_RATE = 16000

resumen_preparacion = []

for ruta_split in ruta_base_splits_usuario.iterdir():
    if not ruta_split.is_dir() or not (ruta_split / "dataset_dict.json").exists():
        continue

    nombre_dataset = ruta_split.name
    ruta_salida = ruta_base_splits_preparados / nombre_dataset

    print("Procesando dataset:", nombre_dataset)

    dataset_split = load_from_disk(str(ruta_split))

    train_inicial = len(dataset_split["train"])
    test_inicial = len(dataset_split["test"])

    # Cargamos los audios desde disco con librosa
    dataset_preparado = dataset_split.map(
        cargar_audio_con_librosa,
        desc=f"Cargando audios de {nombre_dataset}"
    )

    # Eliminamos registros donde el audio no se haya podido cargar
    dataset_preparado = dataset_preparado.filter(
        lambda ejemplo: ejemplo["audio_valido"] == True
    )

    train_final = len(dataset_preparado["train"])
    test_final = len(dataset_preparado["test"])

    # Quitamos columnas auxiliares
    dataset_preparado = dataset_preparado.remove_columns([
        "audio_valido",
        "error_audio"
    ])

    dataset_preparado.save_to_disk(str(ruta_salida))

    resumen_preparacion.append({
        "dataset": nombre_dataset,
        "train_inicial": train_inicial,
        "test_inicial": test_inicial,
        "train_final": train_final,
        "test_final": test_final,
        "audios_descartados_train": train_inicial - train_final,
        "audios_descartados_test": test_inicial - test_final,
        "ruta_preparado": str(ruta_salida)
    })

    print("Train inicial:", train_inicial, "| Train final:", train_final)
    print("Test inicial:", test_inicial, "| Test final:", test_final)
    print("Guardado en:", ruta_salida)
    print("----------------------------------------")

Procesando dataset: alba_serrano_rico

Filter:   0%|          | 0/1044 [00:00<?, ? examples/s]

Filter:   0%|          | 0/261 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/844 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/203 [00:00<?, ? examples/s]

Train inicial: 1044 | Train final: 844
Test inicial: 261 | Test final: 203
Guardado en: C:\lara\datasets_por_usuario_split_preparados\alba_serrano_rico
----------------------------------------
Procesando dataset: alvaro_amoros

Cargando audios de alvaro_amoros:   0%|          | 0/400 [00:00<?, ? examples/s]

C:\Users\abelg\AppData\Local\Temp\ipykernel_15652\2369524765.py:7: UserWarning: PySoundFile failed. Trying audioread instead.
  audio_array, sampling_rate = librosa.load(

Cargando audios de alvaro_amoros:   0%|          | 0/101 [00:00<?, ? examples/s]

Filter:   0%|          | 0/400 [00:00<?, ? examples/s]

Filter:   0%|          | 0/101 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/386 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/100 [00:00<?, ? examples/s]

Train inicial: 400 | Train final: 386
Test inicial: 101 | Test final: 100
Guardado en: C:\lara\datasets_por_usuario_split_preparados\alvaro_amoros
----------------------------------------
Procesando dataset: aurora_montiel_mora

Cargando audios de aurora_montiel_mora:   0%|          | 0/453 [00:00<?, ? examples/s]

Cargando audios de aurora_montiel_mora:   0%|          | 0/114 [00:00<?, ? examples/s]

Filter:   0%|          | 0/453 [00:00<?, ? examples/s]

Filter:   0%|          | 0/114 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/419 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/106 [00:00<?, ? examples/s]

Train inicial: 453 | Train final: 419
Test inicial: 114 | Test final: 106
Guardado en: C:\lara\datasets_por_usuario_split_preparados\aurora_montiel_mora
----------------------------------------
Procesando dataset: cristina_román_durá

Cargando audios de cristina_román_durá:   0%|          | 0/999 [00:00<?, ? examples/s]

Cargando audios de cristina_román_durá:   0%|          | 0/250 [00:00<?, ? examples/s]

Filter:   0%|          | 0/999 [00:00<?, ? examples/s]

Filter:   0%|          | 0/250 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/999 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/250 [00:00<?, ? examples/s]

Train inicial: 999 | Train final: 999
Test inicial: 250 | Test final: 250
Guardado en: C:\lara\datasets_por_usuario_split_preparados\cristina_román_durá
----------------------------------------
Procesando dataset: david_laville

Cargando audios de david_laville:   0%|          | 0/505 [00:00<?, ? examples/s]

Cargando audios de david_laville:   0%|          | 0/127 [00:00<?, ? examples/s]

Filter:   0%|          | 0/505 [00:00<?, ? examples/s]

Filter:   0%|          | 0/127 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/476 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/122 [00:00<?, ? examples/s]

Train inicial: 505 | Train final: 476
Test inicial: 127 | Test final: 122
Guardado en: C:\lara\datasets_por_usuario_split_preparados\david_laville
----------------------------------------
Procesando dataset: enrique_sanchez_fernandez

Cargando audios de enrique_sanchez_fernandez:   0%|          | 0/1262 [00:00<?, ? examples/s]

Cargando audios de enrique_sanchez_fernandez:   0%|          | 0/316 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1262 [00:00<?, ? examples/s]

Filter:   0%|          | 0/316 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1060 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/258 [00:00<?, ? examples/s]

Train inicial: 1262 | Train final: 1060
Test inicial: 316 | Test final: 258
Guardado en: C:\lara\datasets_por_usuario_split_preparados\enrique_sanchez_fernandez
----------------------------------------
Procesando dataset: ernesto_belenguer_bedmar

Cargando audios de ernesto_belenguer_bedmar:   0%|          | 0/1230 [00:00<?, ? examples/s]

Cargando audios de ernesto_belenguer_bedmar:   0%|          | 0/308 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1230 [00:00<?, ? examples/s]

Filter:   0%|          | 0/308 [00:00<?, ? examples/s]

Saving the dataset (0/2 shards):   0%|          | 0/1230 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/308 [00:00<?, ? examples/s]

Train inicial: 1230 | Train final: 1230
Test inicial: 308 | Test final: 308
Guardado en: C:\lara\datasets_por_usuario_split_preparados\ernesto_belenguer_bedmar
----------------------------------------
Procesando dataset: eva_ortiz

Cargando audios de eva_ortiz:   0%|          | 0/509 [00:00<?, ? examples/s]

Cargando audios de eva_ortiz:   0%|          | 0/128 [00:00<?, ? examples/s]

Filter:   0%|          | 0/509 [00:00<?, ? examples/s]

Filter:   0%|          | 0/128 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/477 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/118 [00:00<?, ? examples/s]

Train inicial: 509 | Train final: 477
Test inicial: 128 | Test final: 118
Guardado en: C:\lara\datasets_por_usuario_split_preparados\eva_ortiz
----------------------------------------
Procesando dataset: javier

Cargando audios de javier:   0%|          | 0/476 [00:00<?, ? examples/s]

Cargando audios de javier:   0%|          | 0/120 [00:00<?, ? examples/s]

Filter:   0%|          | 0/476 [00:00<?, ? examples/s]

Filter:   0%|          | 0/120 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/476 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/120 [00:00<?, ? examples/s]

Train inicial: 476 | Train final: 476
Test inicial: 120 | Test final: 120
Guardado en: C:\lara\datasets_por_usuario_split_preparados\javier
----------------------------------------
Procesando dataset: laura_moreno

Cargando audios de laura_moreno:   0%|          | 0/820 [00:00<?, ? examples/s]

Cargando audios de laura_moreno:   0%|          | 0/206 [00:00<?, ? examples/s]

Filter:   0%|          | 0/820 [00:00<?, ? examples/s]

Filter:   0%|          | 0/206 [00:00<?, ? examples/s]

Saving the dataset (0/2 shards):   0%|          | 0/795 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/196 [00:00<?, ? examples/s]

Train inicial: 820 | Train final: 795
Test inicial: 206 | Test final: 196
Guardado en: C:\lara\datasets_por_usuario_split_preparados\laura_moreno
----------------------------------------
Procesando dataset: maria_gertrudis_agullo_esclapez

Cargando audios de maria_gertrudis_agullo_esclapez:   0%|          | 0/1288 [00:00<?, ? examples/s]

Cargando audios de maria_gertrudis_agullo_esclapez:   0%|          | 0/322 [00:00<?, ? examples/s]

Filter:   0%|          | 0/1288 [00:00<?, ? examples/s]

Filter:   0%|          | 0/322 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/1123 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/272 [00:00<?, ? examples/s]

Train inicial: 1288 | Train final: 1123
Test inicial: 322 | Test final: 272
Guardado en: C:\lara\datasets_por_usuario_split_preparados\maria_gertrudis_agullo_esclapez
----------------------------------------
Procesando dataset: pablo_ybarra_gomariz

Cargando audios de pablo_ybarra_gomariz:   0%|          | 0/467 [00:00<?, ? examples/s]

Cargando audios de pablo_ybarra_gomariz:   0%|          | 0/117 [00:00<?, ? examples/s]

Filter:   0%|          | 0/467 [00:00<?, ? examples/s]

Filter:   0%|          | 0/117 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/467 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/117 [00:00<?, ? examples/s]

Train inicial: 467 | Train final: 467
Test inicial: 117 | Test final: 117
Guardado en: C:\lara\datasets_por_usuario_split_preparados\pablo_ybarra_gomariz
----------------------------------------
Procesando dataset: raquel_villegas_gonzalvez

Cargando audios de raquel_villegas_gonzalvez:   0%|          | 0/965 [00:00<?, ? examples/s]

Cargando audios de raquel_villegas_gonzalvez:   0%|          | 0/242 [00:00<?, ? examples/s]

Filter:   0%|          | 0/965 [00:00<?, ? examples/s]

Filter:   0%|          | 0/242 [00:00<?, ? examples/s]

Saving the dataset (0/2 shards):   0%|          | 0/808 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/210 [00:00<?, ? examples/s]

Train inicial: 965 | Train final: 808
Test inicial: 242 | Test final: 210
Guardado en: C:\lara\datasets_por_usuario_split_preparados\raquel_villegas_gonzalvez
----------------------------------------
Procesando dataset: tomás_manuel_bermudez

Cargando audios de tomás_manuel_bermudez:   0%|          | 0/10164 [00:00<?, ? examples/s]

Cargando audios de tomás_manuel_bermudez:   0%|          | 0/2542 [00:00<?, ? examples/s]

Filter:   0%|          | 0/10164 [00:00<?, ? examples/s]

Filter:   0%|          | 0/2542 [00:00<?, ? examples/s]

Saving the dataset (0/4 shards):   0%|          | 0/10164 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/2542 [00:00<?, ? examples/s]

Train inicial: 10164 | Train final: 10164
Test inicial: 2542 | Test final: 2542
Guardado en: C:\lara\datasets_por_usuario_split_preparados\tomás_manuel_bermudez
----------------------------------------
Procesando dataset: verónica_marco

Cargando audios de verónica_marco:   0%|          | 0/3796 [00:00<?, ? examples/s]

Cargando audios de verónica_marco:   0%|          | 0/950 [00:00<?, ? examples/s]

Filter:   0%|          | 0/3796 [00:00<?, ? examples/s]

Filter:   0%|          | 0/950 [00:00<?, ? examples/s]

Saving the dataset (0/2 shards):   0%|          | 0/3796 [00:00<?, ? examples/s]

Saving the dataset (0/1 shards):   0%|          | 0/950 [00:00<?, ? examples/s]

Train inicial: 3796 | Train final: 3796
Test inicial: 950 | Test final: 950
Guardado en: C:\lara\datasets_por_usuario_split_preparados\verónica_marco
----------------------------------------

In [38]:
# Guardamos resumen de la preparación
df_resumen_preparacion = pd.DataFrame(resumen_preparacion)

ruta_resumen_preparacion = ruta_base_splits_preparados / "resumen_preparacion_por_usuario.csv"

df_resumen_preparacion.to_csv(
    ruta_resumen_preparacion,
    index=False,
    encoding="utf-8-sig"
)

print("Resumen guardado en:", ruta_resumen_preparacion)

df_resumen_preparacion

Resumen guardado en: C:\lara\datasets_por_usuario_split_preparados\resumen_preparacion_por_usuario.csv

,dataset,train_inicial,test_inicial,train_final,test_final,audios_descartados_train,audios_descartados_test,ruta_preparado
0,alba_serrano_rico,1044,261,844,203,200,58,C:\lara\datasets_por_usuario_split_preparados\...
1,alvaro_amoros,400,101,386,100,14,1,C:\lara\datasets_por_usuario_split_preparados\...
2,aurora_montiel_mora,453,114,419,106,34,8,C:\lara\datasets_por_usuario_split_preparados\...
3,cristina_román_durá,999,250,999,250,0,0,C:\lara\datasets_por_usuario_split_preparados\...
4,david_laville,505,127,476,122,29,5,C:\lara\datasets_por_usuario_split_preparados\...
5,enrique_sanchez_fernandez,1262,316,1060,258,202,58,C:\lara\datasets_por_usuario_split_preparados\...
6,ernesto_belenguer_bedmar,1230,308,1230,308,0,0,C:\lara\datasets_por_usuario_split_preparados\...
7,eva_ortiz,509,128,477,118,32,10,C:\lara\datasets_por_usuario_split_preparados\...
8,javier,476,120,476,120,0,0,C:\lara\datasets_por_usuario_split_preparados\...
9,laura_moreno,820,206,795,196,25,10,C:\lara\datasets_por_usuario_split_preparados\...
10,maria_gertrudis_agullo_esclapez,1288,322,1123,272,165,50,C:\lara\datasets_por_usuario_split_preparados\...
11,pablo_ybarra_gomariz,467,117,467,117,0,0,C:\lara\datasets_por_usuario_split_preparados\...
12,raquel_villegas_gonzalvez,965,242,808,210,157,32,C:\lara\datasets_por_usuario_split_preparados\...
13,tomás_manuel_bermudez,10164,2542,10164,2542,0,0,C:\lara\datasets_por_usuario_split_preparados\...
14,verónica_marco,3796,950,3796,950,0,0,C:\lara\datasets_por_usuario_split_preparados\...

In [39]:
# Comprobamos que todos los datasets preparados tienen train/test y columnas correctas
ruta_base_splits_preparados = Path("C:/lara/datasets_por_usuario_split_preparados")

for ruta_dataset in ruta_base_splits_preparados.iterdir():
    if not ruta_dataset.is_dir() or not (ruta_dataset / "dataset_dict.json").exists():
        continue

    dataset = load_from_disk(str(ruta_dataset))

    print(ruta_dataset.name)
    print(dataset)
    print("Columnas train:", dataset["train"].column_names)
    print("Columnas test:", dataset["test"].column_names)
    print("----------------------------------------")

alba_serrano_rico
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 844
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 203
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
alvaro_amoros
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 386
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 100
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
aurora_montiel_mora
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 419
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 106
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
cristina_román_durá
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 999
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 250
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
david_laville
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 476
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 122
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
enrique_sanchez_fernandez
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1060
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 258
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
ernesto_belenguer_bedmar
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1230
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 308
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
eva_ortiz
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 477
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 118
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
javier
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 476
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 120
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
laura_moreno
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 795
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 196
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
maria_gertrudis_agullo_esclapez
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1123
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 272
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
pablo_ybarra_gomariz
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 467
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 117
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
raquel_villegas_gonzalvez
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 808
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 210
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
tomás_manuel_bermudez
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 10164
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 2542
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------
verónica_marco
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 3796
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 950
    })
})
Columnas train: ['audio', 'texto']
Columnas test: ['audio', 'texto']
----------------------------------------

## Entrenamiento para cada usuario

In [43]:
# Rutas principales
RUTA_DATASETS_PREPARADOS = Path("C:/lara/datasets_por_usuario_split_preparados")

RUTA_MODELOS_SALIDA = Path("C:/lara/modelos_entrenados/por_usuario_whisper_base")
RUTA_RESULTADOS = Path("C:/lara/resultados/08_entrenamiento_por_usuario_whisper_base")

RUTA_MODELOS_SALIDA.mkdir(parents=True, exist_ok=True)
RUTA_RESULTADOS.mkdir(parents=True, exist_ok=True)

# Modelo base de partida: entrenamiento limpio desde Whisper base
MODELO_BASE = "openai/whisper-base"

# Parámetros de entrenamiento
EPOCAS = 8
LEARNING_RATE = 2e-6

TRAIN_BATCH_SIZE = 2
TEST_BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4

SEED = 42
FP16 = torch.cuda.is_available()

print("Modelo base:", MODELO_BASE)
print("Ruta datasets preparados:", RUTA_DATASETS_PREPARADOS)
print("Ruta modelos salida:", RUTA_MODELOS_SALIDA)
print("Ruta resultados:", RUTA_RESULTADOS)
print("----------------------------------------")
print("Épocas:", EPOCAS)
print("Learning rate:", LEARNING_RATE)
print("Batch train:", TRAIN_BATCH_SIZE)
print("Batch test:", TEST_BATCH_SIZE)
print("Gradient accumulation:", GRADIENT_ACCUMULATION_STEPS)
print("FP16:", FP16)
print("----------------------------------------")
print("GPU disponible:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

Modelo base: openai/whisper-base
Ruta datasets preparados: C:\lara\datasets_por_usuario_split_preparados
Ruta modelos salida: C:\lara\modelos_entrenados\por_usuario_whisper_base
Ruta resultados: C:\lara\resultados\08_entrenamiento_por_usuario_whisper_base
----------------------------------------
Épocas: 8
Learning rate: 2e-06
Batch train: 2
Batch test: 2
Gradient accumulation: 4
FP16: True
----------------------------------------
GPU disponible: True
GPU: NVIDIA GeForce RTX 3060 Laptop GPU

In [44]:
# Cargamos processor y métricas
processor = WhisperProcessor.from_pretrained(
    MODELO_BASE,
    language="Spanish",
    task="transcribe"
)

metric_wer = evaluate.load("wer")
metric_cer = evaluate.load("cer")

print("Processor cargado correctamente")
print("Métricas cargadas correctamente")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Processor cargado correctamente
Métricas cargadas correctamente

In [45]:
@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any
    decoder_start_token_id: int

    def __call__(self, features):
        # Preparamos las características de entrada del audio
        input_features = [
            {"input_features": feature["input_features"]}
            for feature in features
        ]

        batch = self.processor.feature_extractor.pad(
            input_features,
            return_tensors="pt"
        )

        # Preparamos las etiquetas de texto
        label_features = [
            {"input_ids": feature["labels"]}
            for feature in features
        ]

        labels_batch = self.processor.tokenizer.pad(
            label_features,
            return_tensors="pt"
        )

        labels = labels_batch["input_ids"].masked_fill(
            labels_batch.attention_mask.ne(1),
            -100
        )

        # Quitamos el token inicial si ya viene añadido
        if (labels[:, 0] == self.decoder_start_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels

        return batch


data_collator = DataCollatorSpeechSeq2SeqWithPadding(
    processor=processor,
    decoder_start_token_id=processor.tokenizer.pad_token_id
)

print("Data collator creado correctamente")

Data collator creado correctamente

In [46]:
# Convertimos cada muestra al formato que necesita Whisper
def preparar_muestra(batch):
    audio = batch["audio"]

    batch["input_features"] = processor.feature_extractor(
        audio["array"],
        sampling_rate=audio["sampling_rate"]
    ).input_features[0]

    batch["labels"] = processor.tokenizer(batch["texto"]).input_ids

    return batch


# Calculamos WER y CER sobre las predicciones
def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    pred_str = processor.tokenizer.batch_decode(
        pred_ids,
        skip_special_tokens=True
    )

    label_str = processor.tokenizer.batch_decode(
        label_ids,
        skip_special_tokens=True
    )

    wer = metric_wer.compute(
        predictions=pred_str,
        references=label_str
    )

    cer = metric_cer.compute(
        predictions=pred_str,
        references=label_str
    )

    return {
        "wer": wer,
        "cer": cer
    }


print("Funciones de preprocesado y métricas creadas correctamente")

Funciones de preprocesado y métricas creadas correctamente

In [47]:
# Buscamos datasets preparados por usuario para comprobar que están correctos antes de entrenar
rutas_datasets = []

for ruta in RUTA_DATASETS_PREPARADOS.iterdir():
    if ruta.is_dir() and (ruta / "dataset_dict.json").exists():
        rutas_datasets.append(ruta)

rutas_datasets = sorted(rutas_datasets)

print("Datasets encontrados:", len(rutas_datasets))
print("----------------------------------------")

for ruta in rutas_datasets:
    dataset_temp = load_from_disk(str(ruta))

    print("Dataset:", ruta.name)
    print("Train:", len(dataset_temp["train"]))
    print("Test:", len(dataset_temp["test"]))
    print("----------------------------------------")

Datasets encontrados: 15
----------------------------------------
Dataset: alba_serrano_rico
Train: 844
Test: 203
----------------------------------------
Dataset: alvaro_amoros
Train: 386
Test: 100
----------------------------------------
Dataset: aurora_montiel_mora
Train: 419
Test: 106
----------------------------------------
Dataset: cristina_román_durá
Train: 999
Test: 250
----------------------------------------
Dataset: david_laville
Train: 476
Test: 122
----------------------------------------
Dataset: enrique_sanchez_fernandez
Train: 1060
Test: 258
----------------------------------------
Dataset: ernesto_belenguer_bedmar
Train: 1230
Test: 308
----------------------------------------
Dataset: eva_ortiz
Train: 477
Test: 118
----------------------------------------
Dataset: javier
Train: 476
Test: 120
----------------------------------------
Dataset: laura_moreno
Train: 795
Test: 196
----------------------------------------
Dataset: maria_gertrudis_agullo_esclapez
Train: 1123
Test: 272
----------------------------------------
Dataset: pablo_ybarra_gomariz
Train: 467
Test: 117
----------------------------------------
Dataset: raquel_villegas_gonzalvez
Train: 808
Test: 210
----------------------------------------
Dataset: tomás_manuel_bermudez
Train: 10164
Test: 2542
----------------------------------------
Dataset: verónica_marco
Train: 3796
Test: 950
----------------------------------------

In [48]:
resumen_entrenamientos = []

# Entrenamos un modelo independiente para cada dataset de usuario
for ruta_dataset in rutas_datasets:
    nombre_usuario_dataset = ruta_dataset.name

    print("========================================")
    print("Entrenando dataset:", nombre_usuario_dataset)
    print("========================================")

    ruta_modelo_usuario = RUTA_MODELOS_SALIDA / nombre_usuario_dataset
    ruta_resultados_usuario = RUTA_RESULTADOS / nombre_usuario_dataset

    ruta_modelo_usuario.mkdir(parents=True, exist_ok=True)
    ruta_resultados_usuario.mkdir(parents=True, exist_ok=True)

    # Cargamos el dataset preparado
    dataset_usuario = load_from_disk(str(ruta_dataset))

    print(dataset_usuario)

    # Preparamos las muestras para Whisper
    dataset_procesado = dataset_usuario.map(
        preparar_muestra,
        remove_columns=dataset_usuario["train"].column_names,
        desc=f"Preprocesando {nombre_usuario_dataset}"
    )

    print(dataset_procesado)

    # Cargamos Whisper base limpio para este usuario
    model = WhisperForConditionalGeneration.from_pretrained(MODELO_BASE)

    model.generation_config.language = "spanish"
    model.generation_config.task = "transcribe"
    model.generation_config.forced_decoder_ids = processor.get_decoder_prompt_ids(
        language="spanish",
        task="transcribe"
    )

    training_args = Seq2SeqTrainingArguments(
        output_dir=str(ruta_resultados_usuario / "checkpoints"),

        per_device_train_batch_size=TRAIN_BATCH_SIZE,
        per_device_eval_batch_size=TEST_BATCH_SIZE,
        gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,

        learning_rate=LEARNING_RATE,
        num_train_epochs=EPOCAS,

        predict_with_generate=True,
        generation_max_length=225,

        fp16=FP16,

        logging_strategy="steps",
        logging_steps=25,
        report_to="none",

        save_strategy="no",
        eval_strategy="no",

        seed=SEED,
        remove_unused_columns=False
    )

    trainer = Seq2SeqTrainer(
        args=training_args,
        model=model,
        train_dataset=dataset_procesado["train"],
        eval_dataset=None,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        processing_class=processor
    )

    # Entrenamiento
    train_result = trainer.train()

    # Guardamos modelo final y processor
    trainer.save_model(str(ruta_modelo_usuario))
    processor.save_pretrained(str(ruta_modelo_usuario))

    print("Modelo guardado en:", ruta_modelo_usuario)

    # Guardamos métricas de entrenamiento
    train_metrics = train_result.metrics

    with open(ruta_resultados_usuario / "train_metrics.json", "w", encoding="utf-8") as f:
        json.dump(train_metrics, f, indent=4, ensure_ascii=False)

    # Guardamos historial completo de logs
    log_history = trainer.state.log_history

    with open(ruta_resultados_usuario / "log_history.json", "w", encoding="utf-8") as f:
        json.dump(log_history, f, indent=4, ensure_ascii=False)

    df_log_history = pd.DataFrame(log_history)

    df_log_history.to_csv(
        ruta_resultados_usuario / "log_history.csv",
        index=False,
        encoding="utf-8-sig"
    )

    # Evaluación final sobre test
    print("Evaluando sobre test...")

    predicciones = trainer.predict(dataset_procesado["test"])
    test_metrics = predicciones.metrics

    with open(ruta_resultados_usuario / "test_metrics.json", "w", encoding="utf-8") as f:
        json.dump(test_metrics, f, indent=4, ensure_ascii=False)

    # Guardamos predicciones y textos reales del test
    pred_ids = predicciones.predictions
    label_ids = predicciones.label_ids

    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id

    textos_predichos = processor.tokenizer.batch_decode(
        pred_ids,
        skip_special_tokens=True
    )

    textos_reales = processor.tokenizer.batch_decode(
        label_ids,
        skip_special_tokens=True
    )

    df_predicciones = pd.DataFrame({
        "texto_real": textos_reales,
        "texto_predicho": textos_predichos
    })

    df_predicciones.to_csv(
        ruta_resultados_usuario / "predicciones_test.csv",
        index=False,
        encoding="utf-8-sig"
    )

    resumen_entrenamientos.append({
        "dataset": nombre_usuario_dataset,
        "train_rows": len(dataset_procesado["train"]),
        "test_rows": len(dataset_procesado["test"]),
        "epocas": EPOCAS,
        "learning_rate": LEARNING_RATE,
        "train_loss": train_metrics.get("train_loss"),
        "test_loss": test_metrics.get("test_loss"),
        "test_wer": test_metrics.get("test_wer"),
        "test_cer": test_metrics.get("test_cer"),
        "ruta_modelo": str(ruta_modelo_usuario),
        "ruta_resultados": str(ruta_resultados_usuario)
    })

    print("Entrenamiento finalizado:", nombre_usuario_dataset)
    print("WER test:", test_metrics.get("test_wer"))
    print("CER test:", test_metrics.get("test_cer"))
    print("----------------------------------------")

    # Liberamos memoria antes de pasar al siguiente usuario
    del trainer
    del model
    del dataset_usuario
    del dataset_procesado
    del predicciones

    gc.collect()

    if torch.cuda.is_available():
        torch.cuda.empty_cache()

========================================
Entrenando dataset: alba_serrano_rico
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 844
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 203
    })
})

Preprocesando alba_serrano_rico:   0%|          | 0/844 [00:00<?, ? examples/s]

Preprocesando alba_serrano_rico:   0%|          | 0/203 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 844
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 203
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\alba_serrano_rico
Evaluando sobre test...

[transformers] The attention mask is not set and cannot be inferred from input because pad token is same as eos token. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensLogitsProcessor'> to see related `.generate()` flags.
[transformers] A custom logits processor of type <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> has been passed to `.generate()`, but it was also created in `.generate()`, given its parameterization. The custom <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> will take precedence. Please check the docstring of <class 'transformers.generation.logits_process.SuppressTokensAtBeginLogitsProcessor'> to see related `.generate()` flags.

[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer WhisperTokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

Entrenamiento finalizado: alba_serrano_rico
WER test: 1.5011895321173672
CER test: 1.0555139907227293
----------------------------------------
========================================
Entrenando dataset: alvaro_amoros
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 386
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 100
    })
})

Preprocesando alvaro_amoros:   0%|          | 0/386 [00:00<?, ? examples/s]

Preprocesando alvaro_amoros:   0%|          | 0/100 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 386
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 100
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\alvaro_amoros
Evaluando sobre test...

Entrenamiento finalizado: alvaro_amoros
WER test: 0.9901477832512315
CER test: 0.7080916030534351
----------------------------------------
========================================
Entrenando dataset: aurora_montiel_mora
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 419
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 106
    })
})

Preprocesando aurora_montiel_mora:   0%|          | 0/419 [00:00<?, ? examples/s]

Preprocesando aurora_montiel_mora:   0%|          | 0/106 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 419
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 106
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\aurora_montiel_mora
Evaluando sobre test...

Entrenamiento finalizado: aurora_montiel_mora
WER test: 0.9
CER test: 0.5964247020585048
----------------------------------------
========================================
Entrenando dataset: cristina_román_durá
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 999
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 250
    })
})

Preprocesando cristina_román_durá:   0%|          | 0/999 [00:00<?, ? examples/s]

Preprocesando cristina_román_durá:   0%|          | 0/250 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 999
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 250
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\cristina_román_durá
Evaluando sobre test...

Entrenamiento finalizado: cristina_román_durá
WER test: 0.7969374167776299
CER test: 0.5119526925012582
----------------------------------------
========================================
Entrenando dataset: david_laville
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 476
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 122
    })
})

Preprocesando david_laville:   0%|          | 0/476 [00:00<?, ? examples/s]

Preprocesando david_laville:   0%|          | 0/122 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 476
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 122
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\david_laville
Evaluando sobre test...

Entrenamiento finalizado: david_laville
WER test: 0.9145658263305322
CER test: 0.6634225466342255
----------------------------------------
========================================
Entrenando dataset: enrique_sanchez_fernandez
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1060
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 258
    })
})

Preprocesando enrique_sanchez_fernandez:   0%|          | 0/1060 [00:00<?, ? examples/s]

Preprocesando enrique_sanchez_fernandez:   0%|          | 0/258 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 1060
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 258
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\enrique_sanchez_fernandez
Evaluando sobre test...

Entrenamiento finalizado: enrique_sanchez_fernandez
WER test: 1.1317733990147782
CER test: 0.8536900152528453
----------------------------------------
========================================
Entrenando dataset: ernesto_belenguer_bedmar
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1230
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 308
    })
})

Preprocesando ernesto_belenguer_bedmar:   0%|          | 0/1230 [00:00<?, ? examples/s]

Preprocesando ernesto_belenguer_bedmar:   0%|          | 0/308 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 1230
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 308
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\ernesto_belenguer_bedmar
Evaluando sobre test...

Entrenamiento finalizado: ernesto_belenguer_bedmar
WER test: 0.7703324808184143
CER test: 0.447011367803447
----------------------------------------
========================================
Entrenando dataset: eva_ortiz
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 477
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 118
    })
})

Preprocesando eva_ortiz:   0%|          | 0/477 [00:00<?, ? examples/s]

Preprocesando eva_ortiz:   0%|          | 0/118 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 477
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 118
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\eva_ortiz
Evaluando sobre test...

Entrenamiento finalizado: eva_ortiz
WER test: 1.4524959742351047
CER test: 1.1080832823025106
----------------------------------------
========================================
Entrenando dataset: javier
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 476
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 120
    })
})

Preprocesando javier:   0%|          | 0/476 [00:00<?, ? examples/s]

Preprocesando javier:   0%|          | 0/120 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 476
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 120
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\javier
Evaluando sobre test...

Entrenamiento finalizado: javier
WER test: 1.5147453083109919
CER test: 1.173110942633308
----------------------------------------
========================================
Entrenando dataset: laura_moreno
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 795
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 196
    })
})

Preprocesando laura_moreno:   0%|          | 0/795 [00:00<?, ? examples/s]

Preprocesando laura_moreno:   0%|          | 0/196 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 795
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 196
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\laura_moreno
Evaluando sobre test...

Entrenamiento finalizado: laura_moreno
WER test: 0.7482014388489209
CER test: 0.4553343542623788
----------------------------------------
========================================
Entrenando dataset: maria_gertrudis_agullo_esclapez
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 1123
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 272
    })
})

Preprocesando maria_gertrudis_agullo_esclapez:   0%|          | 0/1123 [00:00<?, ? examples/s]

Preprocesando maria_gertrudis_agullo_esclapez:   0%|          | 0/272 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 1123
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 272
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\maria_gertrudis_agullo_esclapez
Evaluando sobre test...

Entrenamiento finalizado: maria_gertrudis_agullo_esclapez
WER test: 1.0772889417360285
CER test: 0.6666294019005031
----------------------------------------
========================================
Entrenando dataset: pablo_ybarra_gomariz
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 467
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 117
    })
})

Preprocesando pablo_ybarra_gomariz:   0%|          | 0/467 [00:00<?, ? examples/s]

Preprocesando pablo_ybarra_gomariz:   0%|          | 0/117 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 467
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 117
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\pablo_ybarra_gomariz
Evaluando sobre test...

Entrenamiento finalizado: pablo_ybarra_gomariz
WER test: 0.8839941262848752
CER test: 0.601059381098411
----------------------------------------
========================================
Entrenando dataset: raquel_villegas_gonzalvez
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 808
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 210
    })
})

Preprocesando raquel_villegas_gonzalvez:   0%|          | 0/808 [00:00<?, ? examples/s]

Preprocesando raquel_villegas_gonzalvez:   0%|          | 0/210 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 808
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 210
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\raquel_villegas_gonzalvez
Evaluando sobre test...

Entrenamiento finalizado: raquel_villegas_gonzalvez
WER test: 1.4635157545605306
CER test: 1.0189633375474083
----------------------------------------
========================================
Entrenando dataset: tomás_manuel_bermudez
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 10164
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 2542
    })
})

Preprocesando tomás_manuel_bermudez:   0%|          | 0/10164 [00:00<?, ? examples/s]

Preprocesando tomás_manuel_bermudez:   0%|          | 0/2542 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 10164
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 2542
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\tomás_manuel_bermudez
Evaluando sobre test...

Entrenamiento finalizado: tomás_manuel_bermudez
WER test: 1.6767941985496375
CER test: 1.352148056409118
----------------------------------------
========================================
Entrenando dataset: verónica_marco
========================================
DatasetDict({
    train: Dataset({
        features: ['audio', 'texto'],
        num_rows: 3796
    })
    test: Dataset({
        features: ['audio', 'texto'],
        num_rows: 950
    })
})

Preprocesando verónica_marco:   0%|          | 0/3796 [00:00<?, ? examples/s]

Preprocesando verónica_marco:   0%|          | 0/950 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 3796
    })
    test: Dataset({
        features: ['input_features', 'labels'],
        num_rows: 950
    })
})

Loading weights:   0%|          | 0/245 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Modelo guardado en: C:\lara\modelos_entrenados\por_usuario_whisper_base\verónica_marco
Evaluando sobre test...

Entrenamiento finalizado: verónica_marco
WER test: 1.4660377358490566
CER test: 1.0209109861646346
----------------------------------------

In [49]:
# Creamos tabla comparativa de resultados
df_comparativa = pd.DataFrame(resumen_entrenamientos)

# Ordenamos de mejor a peor: menor WER y, en empate, menor CER
df_comparativa = df_comparativa.sort_values(
    by=["test_wer", "test_cer"],
    ascending=[True, True]
).reset_index(drop=True)

# Añadimos ranking
df_comparativa.insert(0, "ranking", range(1, len(df_comparativa) + 1))

# Seleccionamos columnas principales
df_comparativa = df_comparativa[
    [
        "ranking",
        "dataset",
        "train_rows",
        "test_rows",
        "epocas",
        "learning_rate",
        "train_loss",
        "test_loss",
        "test_wer",
        "test_cer",
        "ruta_modelo",
        "ruta_resultados"
    ]
]

df_comparativa

,ranking,dataset,train_rows,test_rows,epocas,learning_rate,train_loss,test_loss,test_wer,test_cer,ruta_modelo,ruta_resultados
0,1,laura_moreno,795,196,8,0.000002,4.907775,1.076952,0.748201,0.455334,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
1,2,ernesto_belenguer_bedmar,1230,308,8,0.000002,4.758269,1.155701,0.770332,0.447011,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
2,3,cristina_román_durá,999,250,8,0.000002,4.277984,0.971085,0.796937,0.511953,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
3,4,pablo_ybarra_gomariz,467,117,8,0.000002,4.846664,1.040478,0.883994,0.601059,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
4,5,aurora_montiel_mora,419,106,8,0.000002,6.211674,1.372980,0.900000,0.596425,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
5,6,david_laville,476,122,8,0.000002,5.720062,1.204530,0.914566,0.663423,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
6,7,alvaro_amoros,386,100,8,0.000002,5.545462,1.222744,0.990148,0.708092,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
7,8,maria_gertrudis_agullo_esclapez,1123,272,8,0.000002,5.817067,1.333603,1.077289,0.666629,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
8,9,enrique_sanchez_fernandez,1060,258,8,0.000002,7.162552,1.649371,1.131773,0.853690,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
9,10,eva_ortiz,477,118,8,0.000002,9.388589,2.077331,1.452496,1.108083,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
10,11,raquel_villegas_gonzalvez,808,210,8,0.000002,8.399382,1.856043,1.463516,1.018963,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
11,12,verónica_marco,3796,950,8,0.000002,7.106560,1.565213,1.466038,1.020911,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
12,13,alba_serrano_rico,844,203,8,0.000002,7.081589,1.652198,1.501190,1.055514,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
13,14,javier,476,120,8,0.000002,9.109041,1.912293,1.514745,1.173111,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
14,15,tomás_manuel_bermudez,10164,2542,8,0.000002,4.246551,0.692705,1.676794,1.352148,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...

In [50]:
# Guardamos la tabla comparativa
ruta_comparativa = RUTA_RESULTADOS / "comparativa_resultados_por_usuario.csv"

df_comparativa.to_csv(
    ruta_comparativa,
    index=False,
    encoding="utf-8-sig"
)

print("Comparativa guardada en:", ruta_comparativa)

Comparativa guardada en: C:\lara\resultados\08_entrenamiento_por_usuario_whisper_base\comparativa_resultados_por_usuario.csv

In [51]:
# Reconstruimos la comparativa leyendo los resultados guardados en disco
resultados = []

for ruta_usuario in RUTA_RESULTADOS.iterdir():
    if not ruta_usuario.is_dir():
        continue

    ruta_train_metrics = ruta_usuario / "train_metrics.json"
    ruta_test_metrics = ruta_usuario / "test_metrics.json"

    if not ruta_train_metrics.exists() or not ruta_test_metrics.exists():
        continue

    with open(ruta_train_metrics, "r", encoding="utf-8") as f:
        train_metrics = json.load(f)

    with open(ruta_test_metrics, "r", encoding="utf-8") as f:
        test_metrics = json.load(f)

    resultados.append({
        "dataset": ruta_usuario.name,
        "train_loss": train_metrics.get("train_loss"),
        "test_loss": test_metrics.get("test_loss"),
        "test_wer": test_metrics.get("test_wer"),
        "test_cer": test_metrics.get("test_cer"),
        "runtime_train": train_metrics.get("train_runtime"),
        "runtime_test": test_metrics.get("test_runtime"),
        "ruta_modelo": str(RUTA_MODELOS_SALIDA / ruta_usuario.name),
        "ruta_resultados": str(ruta_usuario)
    })

df_comparativa = pd.DataFrame(resultados)

df_comparativa = df_comparativa.sort_values(
    by=["test_wer", "test_cer"],
    ascending=[True, True]
).reset_index(drop=True)

df_comparativa.insert(0, "ranking", range(1, len(df_comparativa) + 1))

df_comparativa

,ranking,dataset,train_loss,test_loss,test_wer,test_cer,runtime_train,runtime_test,ruta_modelo,ruta_resultados
0,1,laura_moreno,4.907775,1.076952,0.748201,0.455334,920.9771,50.9823,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
1,2,ernesto_belenguer_bedmar,4.758269,1.155701,0.770332,0.447011,1447.3383,88.6210,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
2,3,cristina_román_durá,4.277984,0.971085,0.796937,0.511953,1139.0224,56.7471,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
3,4,pablo_ybarra_gomariz,4.846664,1.040478,0.883994,0.601059,544.8224,28.8597,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
4,5,aurora_montiel_mora,6.211674,1.372980,0.900000,0.596425,473.2008,27.3267,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
5,6,david_laville,5.720062,1.204530,0.914566,0.663423,545.0901,29.6247,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
6,7,alvaro_amoros,5.545462,1.222744,0.990148,0.708092,434.2046,24.1085,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
7,8,maria_gertrudis_agullo_esclapez,5.817067,1.333603,1.077289,0.666629,1308.4725,76.1768,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
8,9,enrique_sanchez_fernandez,7.162552,1.649371,1.131773,0.853690,1232.6261,65.3210,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
9,10,eva_ortiz,9.388589,2.077331,1.452496,1.108083,561.5959,28.8858,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
10,11,raquel_villegas_gonzalvez,8.399382,1.856043,1.463516,1.018963,951.6481,61.1647,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
11,12,verónica_marco,7.106560,1.565213,1.466038,1.020911,4588.2445,324.1363,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
12,13,alba_serrano_rico,7.081589,1.652198,1.501190,1.055514,934.9911,61.6491,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
13,14,javier,9.109041,1.912293,1.514745,1.173111,554.0589,37.2405,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...
14,15,tomás_manuel_bermudez,4.246551,0.692705,1.676794,1.352148,12213.4807,1055.5678,C:\lara\modelos_entrenados\por_usuario_whisper...,C:\lara\resultados\08_entrenamiento_por_usuari...

In [56]:
# Revisamos predicciones de un usuario concreto
usuario_a_revisar = "david_laville"

ruta_predicciones = RUTA_RESULTADOS / usuario_a_revisar / "predicciones_test.csv"

df_pred = pd.read_csv(ruta_predicciones)

df_pred.sample(20, random_state=42)

,texto_real,texto_predicho
18,TENEMOS TANTOS TOMATES QUE LOS TIRAMOS,Tenemos flantos tomates los tiran.
45,SACÓ SU TRACTOR PARA TRABAJAR.,sacó su tráctor a la trabaja.
47,CON MI LÁPIZ DIBUJÓ UN LOBO.,Cómo es lápiz dibujó un agua.
89,FUIMOS A LA SIERRA EN CARRO.,FUIMOS A LA SIRRA EN CARRO.
4,EL ZORRO SE ESCAPÓ DEL ZOO,EN EL TORRO ES JAPÓN EN EL TÓN.
40,¿QUIERES SANDÍA O HELADO?,LLELE LA NÍA OELHADO.
62,ME GUSTA EL TÍTULO DE TU TEBEO.,Me gusta el título de tu tevía.
107,EN NAVIDAD PONEN UN TRINEO EN EL CENTRO.,En la vida ponemos un trineo en el centro.
31,SAQUÉ LA ROPA DEL ESTANQUE.,ya que la ropa del estango.
55,LA PERA ESTÁ MADURA.,LA PERAS ESTÁMADURA.
53,TENER HORARIOS FLEXIBLES.,TENER OORARIO FLECÍBLE.
119,FATIMA PIENSA FACIL,Piencha fácil.
10,LA FAMILIA DE FERNANDO COME FABADA EL FIN DE S...,LA FAMILIA MEJERNADO CON FAVADA EL FINDE SEMA...
90,PEPITO JUEGA CON SUS COMPAÑEROS.,Permito juega con sus compañeros.
109,ME DIO UN CÓLICO POR COMER CANELONES.,Me dio un color rico poco es tan nervioso.
11,ADRIÁN SE COMPRÓ UN DRON.,ADRÍA SE COMPRO UN DRO.
76,REALIZAR UN RECORRIDO EN BARCO POR EL RÍO O EL...,Deirizad un descoglido en vacos por el hilo o...
56,LLEGAMOS A LAS NUEVE DE LA NOCHE.,LLEGAMOS AL ALAD. NUEVETO DE LA LUNCHE.
115,LA TABLA DE TANTA CERA QUE RESBALA,LA TABLA TANTA CERA QUE RESVALA.
0,FUIMOS AL CAMPO EN TIENDA DE CAMPAÑA.,Cuimos al campo en Tilda de Compaccia.

In [54]:
# Recalculamos WER/CER normalizados leyendo las predicciones guardadas
import re

def normalizar_texto(texto):
    texto = str(texto).lower()
    texto = re.sub(r"[^\w\sáéíóúüñ]", " ", texto, flags=re.UNICODE)
    texto = re.sub(r"\s+", " ", texto)
    return texto.strip()


resultados_normalizados = []

for ruta_usuario in RUTA_RESULTADOS.iterdir():
    if not ruta_usuario.is_dir():
        continue

    ruta_predicciones = ruta_usuario / "predicciones_test.csv"
    ruta_test_metrics = ruta_usuario / "test_metrics.json"
    ruta_train_metrics = ruta_usuario / "train_metrics.json"

    if not ruta_predicciones.exists():
        continue

    df_pred = pd.read_csv(ruta_predicciones)

    textos_reales_norm = df_pred["texto_real"].apply(normalizar_texto).tolist()
    textos_predichos_norm = df_pred["texto_predicho"].apply(normalizar_texto).tolist()

    wer_norm = metric_wer.compute(
        predictions=textos_predichos_norm,
        references=textos_reales_norm
    )

    cer_norm = metric_cer.compute(
        predictions=textos_predichos_norm,
        references=textos_reales_norm
    )

    with open(ruta_test_metrics, "r", encoding="utf-8") as f:
        test_metrics = json.load(f)

    with open(ruta_train_metrics, "r", encoding="utf-8") as f:
        train_metrics = json.load(f)

    resultados_normalizados.append({
        "dataset": ruta_usuario.name,
        "train_loss": train_metrics.get("train_loss"),
        "test_loss": test_metrics.get("test_loss"),
        "test_wer_original": test_metrics.get("test_wer"),
        "test_cer_original": test_metrics.get("test_cer"),
        "test_wer_norm": wer_norm,
        "test_cer_norm": cer_norm,
        "num_muestras_test": len(df_pred),
        "ruta_resultados": str(ruta_usuario)
    })


df_comparativa_norm = pd.DataFrame(resultados_normalizados)

df_comparativa_norm = df_comparativa_norm.sort_values(
    by=["test_wer_norm", "test_cer_norm"],
    ascending=[True, True]
).reset_index(drop=True)

df_comparativa_norm.insert(0, "ranking", range(1, len(df_comparativa_norm) + 1))

df_comparativa_norm

,ranking,dataset,train_loss,test_loss,test_wer_original,test_cer_original,test_wer_norm,test_cer_norm,num_muestras_test,ruta_resultados
0,1,david_laville,5.720062,1.204530,0.914566,0.663423,0.528011,0.256977,122,C:\lara\resultados\08_entrenamiento_por_usuari...
1,2,pablo_ybarra_gomariz,4.846664,1.040478,0.883994,0.601059,0.534508,0.233295,117,C:\lara\resultados\08_entrenamiento_por_usuari...
2,3,cristina_román_durá,4.277984,0.971085,0.796937,0.511953,0.539947,0.242208,250,C:\lara\resultados\08_entrenamiento_por_usuari...
3,4,laura_moreno,4.907775,1.076952,0.748201,0.455334,0.552158,0.248527,196,C:\lara\resultados\08_entrenamiento_por_usuari...
4,5,alvaro_amoros,5.545462,1.222744,0.990148,0.708092,0.607553,0.274325,100,C:\lara\resultados\08_entrenamiento_por_usuari...
5,6,aurora_montiel_mora,6.211674,1.372980,0.900000,0.596425,0.620588,0.279457,106,C:\lara\resultados\08_entrenamiento_por_usuari...
6,7,ernesto_belenguer_bedmar,4.758269,1.155701,0.770332,0.447011,0.628002,0.293793,308,C:\lara\resultados\08_entrenamiento_por_usuari...
7,8,enrique_sanchez_fernandez,7.162552,1.649371,1.131773,0.853690,0.874384,0.520377,258,C:\lara\resultados\08_entrenamiento_por_usuari...
8,9,maria_gertrudis_agullo_esclapez,5.817067,1.333603,1.077289,0.666629,0.912604,0.501383,272,C:\lara\resultados\08_entrenamiento_por_usuari...
9,10,javier,9.109041,1.912293,1.514745,1.173111,1.242627,0.805570,120,C:\lara\resultados\08_entrenamiento_por_usuari...
10,11,eva_ortiz,9.388589,2.077331,1.452496,1.108083,1.270531,0.822181,118,C:\lara\resultados\08_entrenamiento_por_usuari...
11,12,alba_serrano_rico,7.081589,1.652198,1.501190,1.055514,1.280730,0.763000,203,C:\lara\resultados\08_entrenamiento_por_usuari...
12,13,raquel_villegas_gonzalvez,8.399382,1.856043,1.463516,1.018963,1.292703,0.803100,210,C:\lara\resultados\08_entrenamiento_por_usuari...
13,14,verónica_marco,7.106560,1.565213,1.466038,1.020911,1.437842,0.965488,950,C:\lara\resultados\08_entrenamiento_por_usuari...
14,15,tomás_manuel_bermudez,4.246551,0.692705,1.676794,1.352148,1.678777,1.343503,2542,C:\lara\resultados\08_entrenamiento_por_usuari...

In [55]:
# Guardamos comparativa con métricas normalizadas
ruta_comparativa_norm = RUTA_RESULTADOS / "comparativa_resultados_por_usuario_normalizada.csv"

df_comparativa_norm.to_csv(
    ruta_comparativa_norm,
    index=False,
    encoding="utf-8-sig"
)

print("Comparativa normalizada guardada en:", ruta_comparativa_norm)

Comparativa normalizada guardada en: C:\lara\resultados\08_entrenamiento_por_usuario_whisper_base\comparativa_resultados_por_usuario_normalizada.csv

## Conclusión

Tras realizar los entrenamientos independientes por usuario, los resultados obtenidos no han sido satisfactorios de forma general.

Aunque algunos modelos reducen parcialmente el error tras normalizar los textos, los valores de WER siguen siendo elevados incluso en los mejores casos. Esto indica que el modelo no está consiguiendo transcribir de forma fiable los audios del dataset cuando se entrena de manera individual por usuario.

Durante el análisis de predicciones se observa que muchas salidas tienen cierta similitud fonética con el texto real, pero presentan errores frecuentes en palabras completas, formas verbales, preposiciones o fragmentos de la frase. En otros casos aparecen predicciones alejadas del texto esperado, lo que sugiere posibles problemas de calidad en los datos.

A partir de los resultados obtenidos, la hipótesis más probable es que el principal factor limitante no sea únicamente la configuración del entrenamiento, sino la calidad del dataset. Es probable que existan audios mal grabados, transcripciones incorrectas, desajustes entre audio y texto, ruido, pronunciaciones muy difíciles de modelar o registros poco consistentes.

Por tanto, antes de seguir probando nuevos entrenamientos, sería necesario realizar una revisión más profunda del dataset original. En concreto, habría que validar la correspondencia entre audio y texto, revisar la calidad de las grabaciones, detectar muestras corruptas o poco audibles y eliminar registros con transcripciones incorrectas.

Como conclusión final, el entrenamiento por usuario no ha demostrado ser una estrategia efectiva con el estado actual de los datos. Para mejorar los resultados sería prioritario trabajar primero sobre la calidad del dataset y, posteriormente, repetir los experimentos con un conjunto de datos más limpio y fiable.